# Generated by Django 5.2.15 on 2026-06-21 22:09

import uuid

from django.db import migrations, models

import apps.vacancies.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "responsibilities",
                    models.JSONField(
                        default=list, validators=[apps.vacancies.validators.validate_string_list]
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        default=list, validators=[apps.vacancies.validators.validate_string_list]
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        default=list, validators=[apps.vacancies.validators.validate_string_list]
                    ),
                ),
                ("location", models.CharField(max_length=160)),
                (
                    "work_format",
                    models.CharField(
                        choices=[
                            ("hybrid", "Hybrid"),
                            ("remote_friendly", "Remote-friendly"),
                            ("on_site", "On-site"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(choices=[("full_time", "Full-time")], max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closing_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title",),
                "indexes": [
                    models.Index(fields=["status", "closing_at"], name="vacancy_public_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "published"), _negated=True),
                            ("published_at__isnull", False),
                            _connector="OR",
                        ),
                        name="vacancy_published_at_required",
                    )
                ],
            },
        ),
    ]
