# Generated by Django 5.2.15 on 2026-06-21 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.vacancies.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_normalized", models.CharField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("portfolio_url", models.URLField(blank=True, max_length=500)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True, choices=[("email", "Email"), ("phone", "Phone")], max_length=16
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early_career", "Early career"),
                            ("mid_level", "Mid-level"),
                            ("senior", "Senior"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, validators=[apps.vacancies.validators.validate_string_list]
                    ),
                ),
                ("optional_message", models.TextField(blank=True, max_length=1200)),
                ("consent_version", models.CharField(blank=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("closed", "Closed"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("application_reference", models.CharField(max_length=32, unique=True)),
                ("status_lookup_secret_hash", models.CharField(max_length=256)),
                ("consented_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
                "indexes": [
                    models.Index(fields=["vacancy", "status"], name="application_review_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vacancy", "email_normalized"),
                        name="uniq_application_vacancy_email",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDraft",
            fields=[
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_normalized", models.CharField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("portfolio_url", models.URLField(blank=True, max_length=500)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True, choices=[("email", "Email"), ("phone", "Phone")], max_length=16
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early_career", "Early career"),
                            ("mid_level", "Mid-level"),
                            ("senior", "Senior"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, validators=[apps.vacancies.validators.validate_string_list]
                    ),
                ),
                ("optional_message", models.TextField(blank=True, max_length=1200)),
                ("consent_version", models.CharField(blank=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("secret_hash", models.CharField(max_length=256, unique=True)),
                ("consent_acknowledged", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("submitted", "Submitted"),
                            ("abandoned", "Abandoned"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [models.Index(fields=["status", "expires_at"], name="draft_expiry_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "submitted"), ("submitted_at__isnull", False)),
                            models.Q(
                                models.Q(("status", "submitted"), _negated=True),
                                ("submitted_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="draft_submitted_at_matches_status",
                    )
                ],
            },
        ),
    ]
