# Generated by Django 5.2.15 on 2026-06-22 13:38

import django.utils.timezone
from django.db import migrations, models


def backfill_last_activity(apps, schema_editor):
    ApplicationDraft = apps.get_model("applications", "ApplicationDraft")
    ApplicationDraft.objects.filter(last_activity_at__isnull=True).update(
        last_activity_at=models.F("updated_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdraft",
            name="creation_key_digest",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="applicationdraft",
            name="credential_revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationdraft",
            name="last_activity_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="applicationdraft",
            name="version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.RunPython(backfill_last_activity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="applicationdraft",
            name="last_activity_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
