# Generated by Django 5.2.15 on 2026-06-23 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_applicationdraft_credential_revoked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftExperienceEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization", models.CharField(max_length=160)),
                ("role_title", models.CharField(max_length=160)),
                ("start_month", models.DateField()),
                ("end_month", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, max_length=600)),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_entries",
                        to="applications.applicationdraft",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["draft", "position"],
                        name="draft_exp_entry_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "position"),
                        name="uniq_draft_experience_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_current", True), ("end_month__isnull", True)),
                            models.Q(("is_current", False), ("end_month__isnull", False)),
                            _connector="OR",
                        ),
                        name="draft_exp_current_end_consistent",
                    ),
                ],
            },
        ),
    ]
