# Generated by Django 5.2.15 on 2026-06-21 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_name_display", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("detected_content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.applicationdraft",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("draft__isnull", False), ("application__isnull", True)),
                            models.Q(("draft__isnull", True), ("application__isnull", False)),
                            _connector="OR",
                        ),
                        name="document_exactly_one_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("draft",),
                        name="uniq_active_document_per_draft",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("application",),
                        name="uniq_active_document_per_application",
                    ),
                ],
            },
        ),
    ]
