# Generated by Django 5.2.15 on 2026-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_draftexperienceentry"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdocument",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="storage_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="applicationdocument",
            index=models.Index(
                fields=["deleted_at", "storage_deleted_at"],
                name="doc_cleanup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("storage_deleted_at__isnull", True),
                    ("deleted_at__isnull", False),
                    _connector="OR",
                ),
                name="doc_storage_deleted_requires_deleted",
            ),
        ),
    ]
